### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by IrosTheBeggar** [jugendhacker/plugin.audio.mstream#3]
Just checked this out.  I cloned it and then zipped it so I could install it in Kodi. After that I clicked the plugin and it worked.  Then I exited out and booted my test mStream server.  I opened Kodi back up and when I clicked on the mStream plugin, I got an error.  I check the log file and this is what I found:

```
1:29:11.144 T:140735807349632   ERROR: GetDirectory - Error getting plugin://plugin.audio.mstream/
01:29:11.144 T:140735807349632   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.mstream/) failed
01:29:11.572 T:123145342009344   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.MissingSchema'>
                                            Error Contents: Invalid URL '/login': No schema supplied. Perhaps you meant http:///login?
                                            Traceback (most recent call last):
                                              File "/Users/paulsori/Library/Application Support/Kodi/addons/plugin.audio.mstream/addon.py", line 32, in <module>
                                                response = requests.post(this_addon.getSetting('server') + '/login', data={'username': this_addon.getSetting('username'), 'password': this_addon.get
Setting('password')}).json()
                                              File "/Users/paulsori/Library/Application Support/Kodi/addons/script.module.requests/lib/requests/api.py", line 112, in post
                                                return request('post', url, data=data, json=json, **kwargs)
                                              File "/Users/paulsori/Library/Application Support/Kodi/addons/script.module.requests/lib/requests/api.py", line 58, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/Users/paulsori/Library/Application Support/Kodi/addons/script.module.requests/lib/requests/sessions.py", line 498, in request
                                                prep = self.prepare_request(req)
                                              File "/Users/paulsori/Library/Application Support/Kodi/addons/script.module.requests/lib/requests/sessions.py", line 441, in prepare_request
                                                hooks=merge_hooks(request.hooks, self.hooks),
                                              File "/Users/paulsori/Library/Application Support/Kodi/addons/script.module.requests/lib/requests/models.py", line 309, in prepare
                                                self.prepare_url(url, params)
                                              File "/Users/paulsori/Library/Application Support/Kodi/addons/script.module.requests/lib/requests/models.py", line 383, in prepare_url
                                                raise MissingSchema(error)
                                            MissingSchema: Invalid URL '/login': No schema supplied. Perhaps you meant http:///login?
                                            -->End of Python script error report<--
01:29:11.612 T:140735807349632   ERROR: GetDirectory - Error getting plugin://plugin.audio.mstream/
```

**Comment by IrosTheBeggar** [comment]
I'm using kodi 17.6 on OSX

**Comment by jugendhacker** [comment]
It looks like you need to setup the server in the plugins settings, klick right on plugin and then settings!
